//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean padClick
        {
            get
            {
                return SteamVR_Actions.default_padClick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Forward
        {
            get
            {
                return SteamVR_Actions.default_Forward;
            }
        }
        
        public virtual SteamVR_Action_Vector2 touchPad
        {
            get
            {
                return SteamVR_Actions.default_touchPad;
            }
        }
        
        public virtual SteamVR_Action_Vector2 moveAction
        {
            get
            {
                return SteamVR_Actions.default_moveAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean buttonClick
        {
            get
            {
                return SteamVR_Actions.default_buttonClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftHandActive
        {
            get
            {
                return SteamVR_Actions.default_LeftHandActive;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightHandActive
        {
            get
            {
                return SteamVR_Actions.default_RightHandActive;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
